import { Component, Input, OnChanges, OnInit } from "@angular/core";
import { ComponentChanges, UnitConversionService } from "@nova-ui/bits";
import {
    Chart,
    ChartAssist,
    GaugeMode,
    GaugeUtil,
    IAccessors,
    IChartAssistSeries,
    IGaugeLabelsPluginConfig,
    IGaugeConfig,
    linearGaugeGridConfig,
    LinearGaugeLabelsPlugin,
    stack,
    XYGrid,
    XYGridConfig,
} from "@nova-ui/charts";

@Component({
    selector: "linear-gauge-vertical-prototype",
    templateUrl: "./linear-gauge-vertical-prototype.component.html",
    styleUrls: ["./linear-gauge-vertical-prototype.component.less"],
})
export class LinearGaugeVerticalPrototypeComponent implements OnChanges, OnInit {
    @Input() public thickness: number;
    @Input() public gaugeConfig: IGaugeConfig;
    @Input() public flipLabels = false;

    public chartAssist: ChartAssist;
    public seriesSet: IChartAssistSeries<IAccessors>[];
    private labelsPlugin: LinearGaugeLabelsPlugin;

    constructor(private unitConversionService: UnitConversionService) { }

    public ngOnChanges(changes: ComponentChanges<LinearGaugeVerticalPrototypeComponent>): void {
        if ((changes.thickness && !changes.thickness.firstChange) || (changes.flipLabels && !changes.flipLabels.firstChange)) {
            const gridConfig = this.chartAssist.chart.getGrid().config();
            if (changes.thickness) {
                gridConfig.dimension.width(this.thickness);
            }
            if (changes.flipLabels) {
                this.labelsPlugin.config.flipLabels = this.flipLabels;
                // reset the margins to accommodate the label direction change
                gridConfig.dimension.margin = {
                    top: 0,
                    right: 0,
                    bottom: 0,
                    left: 0,
                };
            }
            this.chartAssist.chart.updateDimensions();
        }

        if (changes.gaugeConfig && !changes.gaugeConfig.firstChange) {
            this.labelsPlugin.config.disableThresholdLabels = this.gaugeConfig.disableThresholdMarkers;
            this.chartAssist.update(GaugeUtil.updateSeriesSet(this.seriesSet, this.gaugeConfig));
        }
    }

    public ngOnInit(): void {
        const gridConfig = linearGaugeGridConfig(GaugeMode.Vertical, this.thickness) as XYGridConfig;
        gridConfig.dimension.margin.top = 5;
        gridConfig.dimension.margin.bottom = 5;
        const grid = new XYGrid(gridConfig);
        const chart = new Chart(grid);

        this.chartAssist = new ChartAssist(chart, stack);

        const labelConfig: IGaugeLabelsPluginConfig = {
            flipLabels: this.flipLabels,
            // extra clearance for the longer labels generated by the formatter
            clearance: {
                top: 0,
                right: 35,
                bottom: 0,
                left: 35,
            },
        };
        this.labelsPlugin = new LinearGaugeLabelsPlugin(labelConfig);
        this.chartAssist.chart.addPlugin(this.labelsPlugin);

        this.seriesSet = GaugeUtil.assembleSeriesSet(this.gaugeConfig, GaugeMode.Vertical);
        this.seriesSet = GaugeUtil.setThresholdLabelFormatter((d: string) => {
            const conversion = this.unitConversionService.convert(parseInt(d, 10), 1000, 2);
            return this.unitConversionService.getFullDisplay(conversion, "generic");
        }, this.seriesSet);

        this.chartAssist.update(this.seriesSet);
    }
}
