import { CompactType, DisplayGrid, GridsterConfig, GridType } from "angular-gridster2";

export const DEFAULT_GRIDSTER_CONFIG: GridsterConfig = {
    displayGrid: DisplayGrid.None,
    gridType: GridType.VerticalFixed,
    compactType: CompactType.CompactUp,
    margin: 15,
    outerMargin: true,
    outerMarginTop: null,
    outerMarginRight: null,
    outerMarginBottom: null,
    outerMarginLeft: null,
    mobileBreakpoint: 640,
    minCols: 12,
    maxCols: 12,
    minRows: 12,
    fixedRowHeight: 44,
    minItemArea: 1,
    defaultItemCols: 6,
    defaultItemRows: 6,
    keepFixedHeightInMobile: false,
    keepFixedWidthInMobile: false,
    scrollSensitivity: 10,
    scrollSpeed: 20,
    enableEmptyCellClick: false,
    enableEmptyCellContextMenu: false,
    enableEmptyCellDrop: false,
    enableEmptyCellDrag: false,
    emptyCellDragMaxCols: 50,
    emptyCellDragMaxRows: 50,
    ignoreMarginInRow: false,
    draggable: {
        enabled: false,
        ignoreContent: true,
        dragHandleClass: "nui-dashboard__widget--drag-handle",
    },
    resizable: {
        enabled: false,
        handles: {
            s: true,
            e: true,
            n: true,
            w: true,
            se: true,
            ne: true,
            sw: true,
            nw: true,
        },
    },
    swap: false,
    pushItems: true,
    pushResizeItems: true,
    disablePushOnDrag: false,
    disablePushOnResize: false,
    pushDirections: { north: true, east: true, south: true, west: true },
    disableWindowResize: false,
    disableWarnings: false,
    scrollToNewItems: false,
};
