#!/bin/bash
set -e


# Check if dependency argument is provided
if [ -z "$1" ]; then
  echo "Usage: bash $0 <dependency-path>"
  echo "Example: bash $0 packages/bits"
  exit 1
fi

PACKAGE=$1

if [ "$PROJECT_DIR" != "" ]; then
    cd $PROJECT_DIR
    ls
fi

PACKAGE_VERSION=$(node -p "require('./package.json').version")

TGZ_FILE="nova-ui-$PACKAGE-${BUILD_COUNTER}.tgz"

FILE="file:./../$PACKAGE/$TGZ_FILE"
echo "Adding dependency:yarn add $FILE -D"
#yarn add $FILE -D
yarn add file:./../bits/nova-ui-bits-16.0.0-0.tgz -D

#PROJECT_DIR="/packages/charts" BUILD_COUNTER="16.0.0-0" bash scripts/add-dependency packages/bits
