#!/bin/bash
set -e

usage()
{
    echo "Usage: docker-compose run -e BUILD_COUNTER=%build.counter% build npm run compute-version-ci"
    echo "Compute build version from package version and build counter"
    echo
    echo "Options:"
    echo "  -h, --help       [Optional] Show this help message"
}

while [ -n "$1" ]; do
    case "$1" in
    -h|--help)
        usage
        exit
        ;;
    -*)
        echo "Unexpected argument '$1'."
        exit 1
        ;;
    esac
done

cd $PROJECT_DIR

package_version=$(grep -E "\"version\":( )*\"([a-zA-Z0-9\.-]*)\"" package.json | sed -E 's/^.*"([0-9]+\.[0-9]+\.[^"]*).*$/\1/g' )

# Create build number - add build counter to project version, don't add in case of alpha/beta/rc or regular release
if [[ $package_version =~ alpha|beta|rc ]]; then
  computed_version="${package_version}.${BUILD_COUNTER}";
  else
  computed_version=$(echo "$package_version" | sed -E "s/-([a-zA-Z.]*)([0-9]*)/-\1${BUILD_COUNTER}/");
fi

echo "##teamcity[buildNumber '$computed_version']"

# Save new version to package.json to be able create proper npm package
npm --no-git-tag-version version --allow-same-version "$computed_version"
