#!/bin/bash
set -e

usage()
{
    echo "Usage: docker run -v \"\$SSH_AUTH_SOCK:/tmp/ssh_auth_sock/\" -e SSH_AUTH_SOCK=/tmp/ssh_auth_sock -e BUILD_BRANCH=<BUILD_BRANCH> -e PACKAGE_NAME=<PACKAGE_NAME> <IMAGE> deploy-docs"
    echo
    echo "Deploy docs/demo application to apollo-docs.swdev.local with the \"teamcity.rsa\" SSH key"
    echo
    echo "Options:"
    echo "  -h, --help       [Optional] Show this help message"
}

while [ -n "$1" ]; do
    case "$1" in
    -h|--help)
        usage
        exit
        ;;
    -*)
        echo "Unexpected argument '$1'."
        exit 1
        ;;
    esac
done

BRANCH_PATH=$(echo "$CIRCLE_BRANCH" | tr / _)
BITS_BRANCH="./projects/bits/${BRANCH_PATH}"
CHARTS_BRANCH="./projects/charts/${BRANCH_PATH}"
DASHBOARDS_BRANCH="./projects/dashboards/${BRANCH_PATH}"

mkdir nova-docs
cd ./nova-docs
mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

git clone $DOC_SERVICE_REPO .

mkdir --parents ./projects/bits
mv ../packages/bits/sdk/api-docs-ng2 ./projects/bits/
rm -rf $BITS_BRANCH
mv ./projects/bits/api-docs-ng2 $BITS_BRANCH

mkdir --parents ./projects/charts
mv ../packages/charts/sdk/api-docs-ng2 ./projects/charts/
rm -rf $CHARTS_BRANCH
mv ../packages/charts/sdk/api-docs-ng2 $CHARTS_BRANCH

mkdir --parents ./projects/dashboards
mv ../packages/dashboards/sdk/api-docs-ng2 ./projects/dashboards/
rm -rf DASHBOARDS_BRANCH
mv ../packages/dashboards/sdk/api-docs-ng2 $DASHBOARDS_BRANCH

zip -r nova-docs.zip *
mv ./nova-docs.zip ../

git config user.email "circleci@circleci"
git config user.name "${GITHUB_USER_NAME}"
git remote set-url origin https://$GITHUB_USER_NAME:$GITHUB_TOKEN@github.com/solarwinds/apollo-doc-service.git
git add .
git commit -m "add docs"
git push origin main
