#!/bin/bash
set -e

SERVER=http://dev-brn-art-02.swdev.local

usage()
{
    echo "Usage: docker-compose run -e BUILD_BRANCH=%teamcity.build.branch% build npm run publish-ci"
    echo "Create a tarball and publish package to Artifactory"
    echo
    echo "Options:"
    echo "  -h, --help       [Optional] Show this help message"
}


while [ -n "$1" ]; do
    case "$1" in
    -h|--help)
        usage
        exit
        ;;
    -*)
        echo "Unexpected argument '$1'."
        exit 1
        ;;
    esac
done

cd $PROJECT_DIR

# retrieve data from package.json
PACKAGE_NAME=$(node -p "require('./package.json').name")
PACKAGE_VERSION=$(node -p "require('./package.json').version")

case $CIRCLE_BRANCH in
      "release/"*)
          echo Publishing release package
            npm publish ./dist
            ;;

      "main" | "next" | "hotfix/"*)
          echo Publishing $CIRCLE_BRANCH package
            npm publish ./dist --tag $CIRCLE_BRANCH
            ;;
      *)
          echo "Feature branch build - publish skipped"
esac

npm pack ./dist --unsafe-perm

