#!/bin/bash
set -ev

usage()
{
    echo "Publish package to npmjs"
    echo
    echo "Options:"
    echo "  -h, --help       [Optional] Show this help message"
}


while [ -n "$1" ]; do
    case "$1" in
    -h|--help)
        usage
        exit
        ;;
    -*)
        echo "Unexpected argument '$1'."
        exit 1
        ;;
    esac
done

if [ "$PROJECT_DIR" != "" ]; then
    cd $PROJECT_DIR
fi

# retrieve data from package.json
PACKAGE_NAME=$(node -p "require('./dist/package.json').name")
PACKAGE_VERSION=$(node -p "require('./dist/package.json').version")
PACKAGE_LICENSE=$(node -p "require('./dist/package.json').license")

echo -e "//registry.npmjs.org/:_authToken=$NPM_TOKEN\nalways-auth=true" > .npmrc
yarn config set init-license $PACKAGE_LICENSE

npm info $PACKAGE_NAME@$PACKAGE_VERSION version 2>/dev/null && {
    echo "Package $PACKAGE_NAME@$PACKAGE_VERSION does already exist on npmjs.org"
    exit
}

case $CIRCLE_BRANCH in
      "release/"*)
          echo "Publishing release package | $PACKAGE_NAME @ $PACKAGE_VERSION"
            yarn publish ./dist --access public
            ;;

      "main" | "next" | "hotfix/"* | "cci/"*)
          echo "Publishing $CIRCLE_BRANCH package | $PACKAGE_NAME @ $PACKAGE_VERSION"
            yarn publish ./dist --tag $CIRCLE_BRANCH --access public
            ;;
      *)
          echo "Feature branch build - publish skipped"
esac
