#!/bin/bash
set -xe

export SOURCE_BRANCH=test-release-prep
export CIRCLE_BRANCH=$SOURCE_BRANCH
export RELEASE_VERSION=$(node -p "require('./package.json').version")


if [ "$SOURCE_BRANCH" == "" ]; then
      echo "Missing required environment variable SOURCE_BRANCH"
      exit 1
fi

if [ "$RELEASE_BRANCH" == "" ]; then
      echo "Missing required environment variable RELEASE_BRANCH"
      exit 1
fi

if [ "$CIRCLE_BRANCH" == "" ]; then
      echo "Missing required environment variable CIRCLE_BRANCH"
      exit 1
fi

if [ "$INCREMENT_TYPE" == "" ]; then
      echo "Missing required environment variable INCREMENT_TYPE"
      exit 1
fi

if [ "$SOURCE_BRANCH" != "$CIRCLE_BRANCH" ]; then
    echo "ERROR: configuration should be run on the branch that contains the changes (usually main)"
    exit 1
fi

# Merge Changes
if ! git show-ref --quiet $RELEASE_BRANCH; then
    echo "Creating release branch:" $CREATE_RELEASE_BRANCH
    if [ "$CREATE_RELEASE_BRANCH" == "true" ]; then
        echo "Creating $RELEASE_BRANCH"
        git checkout -b $RELEASE_BRANCH
        git push --set-upstream origin $RELEASE_BRANCH
    else
        echo "ERROR: release branch does not exist"
        exit 1
    fi
fi

# initial merge with "ours" strategy to auto-resolve conflicts
#git checkout $SOURCE_BRANCH
#git pull origin $RELEASE_BRANCH --no-rebase -s ours

git checkout $RELEASE_BRANCH
git checkout -b "update-release-files-$RELEASE_VERSION" $RELEASE_BRANCH
git merge $SOURCE_BRANCH --no-edit -X theirs

# Set Release Version
yarn run set-release-versions-ci

# Set Release Dependency Versions
yarn run set-dependency-versions-ci

# Commit and Push Release Branch Changes
git commit -am "update files for version $RELEASE_VERSION"
git push --set-upstream origin "update-release-files-$RELEASE_VERSION"

response=$(curl -L --silent \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GITHUB_WRITE_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/solarwinds/nova/pulls \
  -d "{\"title\":\"Amazing new feature\",\"body\":\"Please pull these awesome changes in!\",\"head\":\"update-release-files-$RELEASE_VERSION\",\"base\":\"$RELEASE_BRANCH\"}")

pr1url=$(echo $response | grep html_url | grep nova/pull | xargs | cut -d ' ' -f 2)

echo ""
echo "RELEASE PR: ${pr1url}"

exit

# Increment source branch version
git checkout $SOURCE_BRANCH
git checkout -b "inc-develop-version-$RELEASE_VERSION" $SOURCE_BRANCH

yarn run set-source-versions-ci

# Set source dependency versions
yarn run set-dependency-versions-ci

# Push source branch changes
git commit -am 'increment develop versions'
git push --set-upstream origin "inc-develop-version-$RELEASE_VERSION"

# create PR inc-develop-version -> source
#gh pr create --title "Increment develop version $RELEASE_VERSION" --body ""
