#!/bin/bash
set -xe
export RELEASE_VERSION=$(node -p "require('./package.json').version")

if [ "$SOURCE_BRANCH" == "" ]; then
      echo "Missing required environment variable SOURCE_BRANCH"
      exit 1
fi

if [ "$RELEASE_BRANCH" == "" ]; then
      echo "Missing required environment variable RELEASE_BRANCH"
      exit 1
fi

if [ "$CIRCLE_BRANCH" == "" ]; then
      echo "Missing required environment variable CIRCLE_BRANCH"
      exit 1
fi

if [ "$INCREMENT_TYPE" == "" ]; then
      echo "Missing required environment variable INCREMENT_TYPE"
      exit 1
fi

if [ "$SOURCE_BRANCH" != "$CIRCLE_BRANCH" ]; then
    if [[ $string != *"cci-release"* ]]; then
        echo "ERROR: configuration should be run on the branch that contains the changes (usually main)"
        exit 1
    fi
fi

# Merge Changes
echo "Merge Changes"

if ! git show-ref --quiet $RELEASE_BRANCH; then
    echo "Creating release branch:" $CREATE_RELEASE_BRANCH
    if [ "$CREATE_RELEASE_BRANCH" == "true" ]; then
        echo "Creating $RELEASE_BRANCH"
        git checkout -b $RELEASE_BRANCH
        git push --set-upstream origin $RELEASE_BRANCH
    else
        echo "ERROR: release branch does not exist"
        exit 1
    fi
fi

# initial merge with "ours" strategy to auto-resolve conflicts
echo "initial merge with 'ours' strategy to auto-resolve conflicts"
git checkout $SOURCE_BRANCH
git pull origin $RELEASE_BRANCH --no-rebase -s ours
git checkout $RELEASE_BRANCH
git merge $SOURCE_BRANCH --no-edit -X theirs

# Set Release Version
echo "Set Release Version $RELEASE_VERSION"
yarn run set-release-versions-ci

# Set Release Dependency Versions
echo "Set Next Release Dependency Versions $RELEASE_VERSION"
yarn run set-dependency-versions-ci

# Commit and Push Release Branch Changes
echo "Commit and Push Release Branch Changes $RELEASE_VERSION"
git commit -am "update files for version $RELEASE_VERSION"
git push --verbose

# Increment source branch version
echo "Increment source branch version"
git checkout $SOURCE_BRANCH
yarn run set-source-versions-ci

# Set source dependency versions
echo "Set source dependency versions"
yarn run set-dependency-versions-ci

# Push source branch changes
echo "Push source branch changes"
git commit -am 'increment develop versions' && git push origin $SOURCE_BRANCH
