#!/bin/bash

export SOURCE_BRANCH=`git branch --show-current`
export INCREMENT_TYPE=`cat .circleci/config.yml | grep -oP '^ *INCREMENT_TYPE: \K.+'`
export RELEASE_BRANCH=`cat .circleci/config.yml | grep -oP '^ *RELEASE_BRANCH: \K.+'`
export CIRCLE_BRANCH=$SOURCE_BRANCH

yarn run release-prep-ci
