#!/bin/bash
set -e

SCRIPTS=$(dirname $0)

paths=$(node -p "require('./scripts/projects.json').map(p => p.path).join(' ')")

for p in $paths; do
    echo Setting source version in $p
    bash $SCRIPTS/set-version --prerelease-id 1 -p $p
done
