#!/bin/bash
set -e

usage() {
    echo "Usage: verify-package"
    echo
    echo "Verify content of package in project folder vs npm public repo content"
    echo
    echo "Expects assembled package to be present in ./dist and to be already published into public npm repo"
    echo
    echo "Options:"
    echo "  -h, --help              print usage info"
}

while [ -n "$1" ]; do
    case "$1" in
    -h | --help)
        usage
        exit
        ;;
    -*)
        echo "Unexpected argument '$1'."
        exit 1
        ;;
    esac
done

set -x

cd $PROJECT_DIR

pkg_name=$(node -p 'const pkg = require("./package.json"); `${pkg.name}@${pkg.version}`;')
pkg_file=$(node -p 'const pkg = require("./package.json"); `${pkg.name}@${pkg.version}.tgz`.replace(/[^\w\d.]/g, "-").replace(/^-/, "");')

if [ -e ./compare/ ]; then
    rm -rf ./compare/
fi

mkdir compare compare/local compare/public

echo "packing local .tgz"
npm pack ../dist
mv ./$pkg_file ./local-$pkg_file

echo "getting public .tgz for $pkg_name"
npm pack $pkg_name
mv ./$pkg_file ./public-$pkg_file
npm view $pkg_name name version dist.tarball dist.shasum dist.integrity

echo "unpacking local .tgz"
tar -zxf "local-$pkg_file" -C ./local

echo "unpacking public .tgz"
tar -zxf "public-$pkg_file" -C ./public

echo "comparing"
diff=$(diff -qr ./local ./public)

if [ "$diff" != "" ]; then
    echo "found differences"
    echo $diff
    exit 3
fi

echo "no differences found"
